# Generated by Django 4.1.6 on 2023-02-18 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productdir_name',
            new_name='product_name',
        ),
    ]
